feat(token_storage): return error reason
ueberauth/guardian_db pull request #120
Opened 2021-02-01 08:47 UTC by cyberhck

Hello there,
This is my first PR in elixir ecosystem so if I'm missing something, please let me know.

So I got stuck for almost a day because of `:token_storage_failure` and no clue how to proceed, what helped is when I modified guardian_db to log the reason out.

Currently it's eating the error reason and not telling user why.

Normally I'd be like:
![image](https://user-images.githubusercontent.com/3640284/106434864-ae807380-64a4-11eb-8712-db2085127b4c.png)

But because it's very important to not have this kind of error eating stuff, I want to return the reason instead.

Please have a look :slightly_smiling_face:

2021-02-01 12:47 UTC, Hanspagh requested changes
Hi @cyberhck and welcome to the community.
Thank you for the work, I think this is a reasonable thing to excpect when returning an error.
Two comments
1. Would you mind adding the `error_reson` to `destoy_token` as well to align our output.
2. Add an entry into the changelog, since this is a beaking change for anybody matching on the the `{:error, :token_storage_failure}` tuple, will need to make a version 2.1.0

2021-03-15 14:19 UTC, Hanspagh commented
@cyberhck ping

2021-03-16 06:27 UTC, cyberhck commented
oh hello @Hanspagh I'm sorry, I got incredibly busy and hadn't had a chance to play around with elixir.

I'm not sure if I'll be able to get back to this any time soon as I'm working with golang primarily now, please feel free to close it or push new commits and merge.

If I do get some free time and this is still open, I'll try to add it, however I can't make any promises :wink:

2021-05-14 09:23 UTC, yordis commented
@Hanspagh we may want to take this, but since introduces breaking changes from the caller, we should be careful and collect information about potential issues with Guardian as well abstraction as well

2021-07-30 04:36 UTC, cyberhck commented
Hello there, I moved away from elixir and made up my mind that I'm not going to be doing elixir (I have my reasons), I'll probably also not going to be getting back to this PR feel free to do whatever you please :slightly_smiling_face:

2021-07-30 04:53 UTC, yordis commented
This will break the caller pattern matching, therefore, it is a breaking change.

> I'm not going to be doing elixir (I have my reasons)

Good luck in your adventure, also unnecessary parenthesis, we all have our reasons, best wishes.

2021-07-30 04:53 UTC, closed without merging