feat(migration_name): allow migrations with custom table name
ueberauth/guardian_db pull request #124
Opened 2021-03-30 01:41 UTC by aleDsz

As requested from issue, this PR allows to use migration with custom schema names from the config. I also added the `temporary_env` dependency that allows to test temporary configs from the application.

Feel free to make changes :) 

Closes #118.

2021-03-30 16:33 UTC, yordis requested changes

2021-03-30 16:33 UTC, yordis commented on lib/mix/tasks/guardian_db.gen.migration.ex
> +        |> Keyword.get(:schema_name, "guardian_tokens")
I would suggest to add some documentation about it

2021-03-31 02:27 UTC, aleDsz commented on lib/mix/tasks/guardian_db.gen.migration.ex
> +        |> Keyword.get(:schema_name, "guardian_tokens")
Hmmm, where's the best location for it? README or `moduledoc`?

2021-03-31 16:41 UTC, yordis commented on lib/mix/tasks/guardian_db.gen.migration.ex
> +        |> Keyword.get(:schema_name, "guardian_tokens")
For the most part, moduledoc first and then README

2021-04-04 17:58 UTC, yordis approved these changes

2021-04-04 17:58 UTC, merged

2021-04-04 17:58 UTC, yordis commented
🚀 🚀 🚀 🚀 🚀