Storage adapter
ueberauth/guardian_db pull request #126
Opened 2021-05-09 16:38 UTC by alexfilatov

Just adding an [storage adapter](https://github.com/ueberauth/guardian_db/issues/119#issuecomment-809875685) (by @aleDsz) so my Redis plugin could work with the `guardian_db` package as a dependency (currently it's using dependency from my fork).

2021-05-09 17:47 UTC, yordis commented
🚀 🚀 🚀 🚀 🚀 🚀  Lets document every callback and add some explanation of what each callback suppose to do

2021-05-13 21:35 UTC, alexfilatov commented
hey @yordis, just added docs, please have a look and let me know if I need to change smth. thanks!

2021-05-14 02:06 UTC, aleDsz submitted a review, later dismissed
This is great!!! ❤️ 💚 💙 💜 🖤

2021-05-14 03:00 UTC, yordis requested changes
Left some comments, I love it!

2021-05-14 03:00 UTC, yordis commented on README.md
> +Apart from this you will need to configure [Redis connection for `guardian_redis`](https://github.com/alexfilatov/guardian_redis#configuration)
Let's add a section after `### Create your own Repo` called something like `### Adapters` where people could add their adapters for discoverability.

If they want to understand the benefits, they should read those repos intead

2021-05-14 03:00 UTC, yordis commented on README.md
> +You need to implement only 5 methods to make Guardian.DB working with your preferred storage.
```suggestion
You need to implement the `Guardian.DB.Adapter` behavior working with your preferred storage.     
```

Just in case, it becomes 4 or 7, also faster to find the behavior definition.

2021-05-14 09:16 UTC, alexfilatov commented on README.md
> +Apart from this you will need to configure [Redis connection for `guardian_redis`](https://github.com/alexfilatov/guardian_redis#configuration)
added `### Adapters`, please let me know if this is ok @yordis

2021-05-14 09:18 UTC, yordis approved these changes
🚀 🚀 🚀 🚀 🚀 🚀 🚀

2021-05-14 09:19 UTC, merged