Rename adapter to repo
ueberauth/guardian_db pull request #128
Opened 2021-05-15 20:22 UTC by yordis

I am following the footsteps of Ecto on this one, and be more clear about what we are trying to do.

We use adapter word in order to refer to the design pattern (I get that part), but we call it repo everywhere because that is what we are trying to swap using the Adapter pattern.

2021-05-15 20:22 UTC, yordis commented
@alexfilatov please share some 1+

2021-05-15 21:03 UTC, alexfilatov reviewed
Yeah, I understand the change. But in this case if we took out behaviour from the project it will stop working. Maybe give this responsibility to smth else? @yordis

2021-05-16 14:22 UTC, doomspork requested changes
I'm not sure I see the benefit of this PR @yordis, can you expand on the goal here?

Changing `Adapter` to `Repo` is the wrong change here I fear. Given that in Elixir most people are familiar with `Ecto.Repo` when using databases, calling this file in `Guardian.DB` `Repo` is _very_ confusing and it hides what the actual code does: provide an adapter. The original code refers to it as `repo` because it always was an `Ecto.Repo`, that is no longer the case.

When we look at this in code I find this to be very confusing:

```elixir
@behaviour Guardian.DB.Repo
```

Whereas this tells me we're using an adapter of some sort, not a derivative of `Ecto.Repo`:
```elixir
@behaviour Guardian.DB.Adapter
```
Furthermore, I'd like to avoid introducing things like 80 character line limits to markdown files as you've done in the README. This just introduces unnecessary change without provide any benefit.

2021-05-16 14:22 UTC, doomspork commented on README.md
> +`application was not loaded/started` error.
Can we drop the changes to this file @yordis? We don't need to enforce a line limit in our markdown files.

2021-05-16 14:27 UTC, doomspork commented on lib/guardian/db.ex
> -  def repo do
Re-reading your PR it sounds like renaming this function and the config option to something other than `repo` would be the solution.

Adapter would suffice :+1:

2021-05-16 22:29 UTC, closed without merging