Remove part of #34 since the original issue has been fixed in guardian
ueberauth/guardian_db pull request #40
Opened 2017-01-13 16:29 UTC by Moxide

See #39

2017-01-14 16:31 UTC, doomspork requested changes
Thank you @Moxide!  One small change and then we should be good.

2017-01-14 16:31 UTC, doomspork commented on lib/guardian_db.ex
> +      { :error, _ } -> { :error, :token_storage_failure }
Could you please remove the spaces inside these tuples?

https://github.com/christopheradams/elixir_style_guide#spaces

2017-01-14 17:32 UTC, Moxide commented on lib/guardian_db.ex
> +      { :error, _ } -> { :error, :token_storage_failure }
Ok ;-) Also cleaned code in other places in the file.

2017-01-16 05:40 UTC, merged

2017-01-16 05:40 UTC, doomspork commented
Thank you @Moxide 😀

2017-01-16 07:50 UTC, Moxide commented
You're welcome ;-)

2017-01-19 18:15 UTC, imranismail commented
This needs a dependency bump for guardian. Need to cut out a release for both guardian and guardian_db.

2017-01-19 18:20 UTC, doomspork commented
I am going to work on that today or tomorrow @imranismail 👍