Update the readme and documentation for guardian 1.0
ueberauth/guardian_db pull request #52
Opened 2017-06-12 15:57 UTC by hassox

This should not be merged until Guardian 1.0 has shipped.

2017-06-12 22:53 UTC, doomspork commented on README.md
> +applications database to prevent playback.
I think you want "application's" here.

2017-06-12 22:53 UTC, doomspork commented on README.md
> +**Do not run the migration yet.** You also need to finish your setup first.
This doesn't read quite right, what about something like:

**Do not run the migration yet**, we need to complete our setup first:

2017-06-12 22:53 UTC, doomspork commented on README.md
> +         sweep_interval: 60 # minutes. 60 default
You could combine these two fragments: `# default: 60 minutes`

2017-06-12 22:53 UTC, doomspork commented on README.md
> +To sweep expired tokens from your db you should add `GuardianDb` to your supervision tree.
Did you mean `GuardianDb.ExpiredSweeper`?

2017-06-12 22:53 UTC, doomspork commented on README.md
> +GuardianDb works by hooking into the lifecycle of your token module.
In other places `GuardianDb` is in backticks, did you want to do that here too?

2017-06-12 22:53 UTC, doomspork commented on README.md
> +You'll need to add it to
I think you'll want a colon here.

2017-06-13 02:13 UTC, hassox commented
:metal: Thanks dude. Updated.

2017-09-07 16:37 UTC, doomspork requested changes

2017-09-07 16:37 UTC, doomspork commented on mix.exs
> +    [{:guardian, "~> 0.14 or >= 1.0"},
Do we need to change this to just `1.0`?

2017-09-11 16:56 UTC, hassox commented
@doomspork any other changes needed on this one?

2017-09-11 17:28 UTC, doomspork approved these changes
You're good to go @hassox 👍

2017-09-11 18:29 UTC, merged