Update README.md to use the appropriate migration command
ueberauth/guardian_db pull request #74
Opened 2017-11-30 19:45 UTC by bechurch

## Overview
This is two problems:
1. The readme gives the wrong command to be run for migrations
1. The error gives the wrong command to be run also due to being case sensitive

### Errors
![image](https://user-images.githubusercontent.com/1325608/33451283-68c0bfbc-d5c3-11e7-8556-0286bea460d4.png)
![image](https://user-images.githubusercontent.com/1325608/33451388-c327556a-d5c3-11e7-8c77-80f50cee6729.png)

### Success
```bash
mix guardian.DB.gen.migration
* creating priv/repo/migrations
* creating priv/repo/migrations/20171130193417_guardiandb.exs
```

2017-11-30 19:58 UTC, yordis requested changes
I think it should be lowercase DB as mix feedback was telling your, right ?!

2017-12-18 02:12 UTC, bechurch commented
@yordis Unfortunately not 😞 The capital `DB` was required for the command to run.

2017-12-18 02:14 UTC, yordis commented
@bechurch could you open an issue on elixir related to this? The error message is wrong technically ...

2017-12-18 03:25 UTC, starbelly commented
@bechurch I have a PR that fixes this, I'll go ahead and get it finished.

2017-12-27 20:08 UTC, yordis commented
This is fixed on `master` waiting for release

2017-12-27 20:08 UTC, closed without merging