Add back support for configuring DB prefix:
ueberauth/guardian_db pull request #86
Opened 2018-02-13 17:54 UTC by jamesvl

## Description

I noticed the "prefix" setting described in the [config section of the docs|https://hexdocs.pm/guardian_db/1.1.0/Guardian.DB.html#module-config] does not actually change anything.

This prevents me from upgrading to guardian_db 1.x from the < 1.0 version, which did support it.

## Proposed Solution

The code modifies the Token module to look up and use the configuration for the prefix. It defaults to `nil`, so all existing configurations should continue to work.

It also adds a bit of logic to the migration generator so that the prefix is included there as well.

### Contributing

I'm not sure if you'd prefer this PR from a branch off of master or some other format - let me know and I'll adjust accordingly.

2018-02-13 18:21 UTC, yordis requested changes

2018-02-13 18:21 UTC, yordis commented on lib/guardian/db/token.ex
> +    qry =
do not abbreviate words please. It makes it harder for non-english speakers to understand.

2018-02-13 18:21 UTC, yordis commented on lib/guardian/db/token.ex
> +    qry =
Wouldn't be better to do

```elixir
query = 
  query_schema()
  |> where([token], token.jti == ^jti and token.aud == ^aud)
  |> Map.put(:prefix, prefix())
```
@jamesvl @ueberauth/core any opinions

2018-02-13 18:23 UTC, yordis commented
@jamesvl thank you very much for the support.

cc: @ueberauth/core

2018-02-13 18:30 UTC, jamesvl commented on lib/guardian/db/token.ex
> +    qry =
Good point - I'll change that.

2018-02-13 18:31 UTC, jamesvl commented on lib/guardian/db/token.ex
> +    qry =
That reads more cleanly to me, yes.

2018-02-14 17:07 UTC, jamesvl commented
Code updated according to pull request comments. Let me know if there's anything else you'd like to see.

2018-03-21 00:05 UTC, jamesvl commented
Any updates here?

2018-03-21 03:06 UTC, yordis commented
@ueberauth/core the PR was ready to merge.

2018-03-21 03:06 UTC, yordis approved these changes

2018-03-22 00:58 UTC, merged

2018-03-22 00:58 UTC, doomspork commented
Thank you @jamesvl and @yordis 😁